from __future__ import annotations

from typing import Protocol, Optional, Sequence

from app.infrastructure.database.models import TrendKeyword


class KeywordRepository(Protocol):
    """Repository interface for TrendKeyword persistence."""

    async def get_by_id(self, keyword_id: int) -> Optional[TrendKeyword]: ...
    async def list_all(self, is_active: Optional[bool] = None, limit: int = 100, offset: int = 0) -> Sequence[TrendKeyword]: ...
    async def list_due_for_crawl(self, platform: Optional[str] = None) -> Sequence[TrendKeyword]: ...
    async def create(self, keyword: TrendKeyword) -> TrendKeyword: ...
    async def update(self, keyword: TrendKeyword) -> TrendKeyword: ...
    async def delete(self, keyword_id: int) -> bool: ...
    async def bulk_create(self, keywords: list[TrendKeyword]) -> list[TrendKeyword]: ...
