from __future__ import annotations

from typing import Protocol, Optional, Sequence

from app.infrastructure.database.models import CrawlTask, CrawlTaskLog


class TaskRepository(Protocol):
    """Repository interface for CrawlTask persistence."""

    async def get_by_id(self, task_id: int) -> Optional[CrawlTask]: ...
    async def list_by_status(self, status: Optional[str] = None, limit: int = 50, offset: int = 0) -> Sequence[CrawlTask]: ...
    async def list_by_keyword(self, keyword_id: int) -> Sequence[CrawlTask]: ...
    async def create(self, task: CrawlTask) -> CrawlTask: ...
    async def update(self, task: CrawlTask) -> CrawlTask: ...
    async def add_log(self, task_id: int, level: str, message: str) -> CrawlTaskLog: ...
    async def get_logs(self, task_id: int, limit: int = 100) -> Sequence[CrawlTaskLog]: ...
