"""initial tables

Revision ID: 0928faa6e124
Revises: 
Create Date: 2026-04-14 18:28:06.015279
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0928faa6e124'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False, comment='Platform: xhs/dy/bili/wb/ks/tieba/zhihu'),
    sa.Column('cookies', sa.Text(), nullable=False, comment='Encrypted cookies string'),
    sa.Column('login_type', sa.String(length=16), nullable=False, comment='Login type: qrcode/phone/cookie'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='Status: active/expired/blocked'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Last usage time'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Total usage count'),
    sa.Column('rotation_strategy', sa.String(length=32), nullable=False, comment='Rotation: round_robin/least_used/random'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='Remark'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_platform'), 'accounts', ['platform'], unique=False)
    op.create_table('cleaned_trend_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='Source type: note/video/article'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='Original data ID in MediaCrawler tables'),
    sa.Column('source_platform', sa.String(length=32), nullable=False, comment='Source platform'),
    sa.Column('keyword', sa.String(length=255), nullable=False, comment='Keyword that triggered this crawl'),
    sa.Column('crawl_task_id', sa.Integer(), nullable=False, comment='FK to crawl_tasks.id'),
    sa.Column('title', sa.Text(), nullable=True, comment='Title of the content'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI-generated summary'),
    sa.Column('topics', sa.String(length=1024), nullable=True, comment='Comma-separated topic tags'),
    sa.Column('sentiment', sa.String(length=16), nullable=True, comment='Sentiment: positive/negative/neutral'),
    sa.Column('trend_score', sa.Float(), nullable=False, comment='Trend score calculated from engagement metrics'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='Snapshot of original data'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaned_trend_data_crawl_task_id'), 'cleaned_trend_data', ['crawl_task_id'], unique=False)
    op.create_index(op.f('ix_cleaned_trend_data_keyword'), 'cleaned_trend_data', ['keyword'], unique=False)
    op.create_index(op.f('ix_cleaned_trend_data_source_id'), 'cleaned_trend_data', ['source_id'], unique=False)
    op.create_index(op.f('ix_cleaned_trend_data_source_platform'), 'cleaned_trend_data', ['source_platform'], unique=False)
    op.create_table('crawl_task_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='FK to crawl_tasks.id'),
    sa.Column('level', sa.String(length=16), nullable=False, comment='Log level: info/warning/error/success'),
    sa.Column('message', sa.Text(), nullable=False, comment='Log message'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_task_logs_task_id'), 'crawl_task_logs', ['task_id'], unique=False)
    op.create_table('crawl_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False, comment='FK to trend_keywords.id'),
    sa.Column('keyword', sa.String(length=255), nullable=False, comment='Snapshot of keyword at task creation'),
    sa.Column('platform', sa.String(length=32), nullable=False, comment='Target platform'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='Status: pending/running/completed/failed/cancelled'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='Celery task ID'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Crawl config: login_type, headless, etc.'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='FK to accounts.id'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Task start time'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Task completion time'),
    sa.Column('result_summary', sa.JSON(), nullable=True, comment='Result summary: count, errors, etc.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_tasks_keyword_id'), 'crawl_tasks', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_platform'), 'crawl_tasks', ['platform'], unique=False)
    op.create_table('trend_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.String(length=32), nullable=False, comment='Business keyword ID, e.g. KW_0001'),
    sa.Column('keyword', sa.String(length=255), nullable=False, comment='Keyword text'),
    sa.Column('normalized_keyword', sa.String(length=255), nullable=False, comment='Normalized keyword form'),
    sa.Column('topic_cluster', sa.String(length=64), nullable=False, comment='Topic cluster, e.g. ingredient_technology, anti_aging_frontier'),
    sa.Column('trend_type', sa.String(length=32), nullable=False, comment='Trend type: ingredient/claim/scenario/category/risk_compliance'),
    sa.Column('report_id', sa.String(length=64), nullable=False, comment='Source report ID, e.g. RPT_20260413_01'),
    sa.Column('report_publish_date', sa.String(length=32), nullable=True, comment='Report publish date'),
    sa.Column('signal_period_type', sa.String(length=32), nullable=False, comment='Signal period: annual/monthly/special_topic/cross_period'),
    sa.Column('signal_period_label', sa.String(length=64), nullable=False, comment='Signal period label, e.g. 2026 annual'),
    sa.Column('time_granularity', sa.String(length=32), nullable=False, comment='Time granularity: annual/monthly/special_topic'),
    sa.Column('source_scope', sa.String(length=64), nullable=False, comment='Source scope: industry_research/douyin/xiaohongshu etc.'),
    sa.Column('priority', sa.String(length=16), nullable=False, comment='Priority: high/medium/low'),
    sa.Column('confidence', sa.String(length=16), nullable=False, comment='Confidence: high/medium/low'),
    sa.Column('suggested_platforms', sa.String(length=255), nullable=False, comment='Pipe-separated platforms: xiaohongshu|douyin|industry_news'),
    sa.Column('query_variants', sa.String(length=1024), nullable=False, comment='Pipe-separated query variants'),
    sa.Column('crawl_goal', sa.String(length=32), nullable=False, comment='Crawl goal: trend_discovery/market_validation/risk_monitoring'),
    sa.Column('risk_flag', sa.String(length=16), nullable=False, comment='Risk flag: low/medium/high'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether keyword is active'),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True, comment='Last crawl time'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_keywords_keyword_id'), 'trend_keywords', ['keyword_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_keywords_keyword_id'), table_name='trend_keywords')
    op.drop_table('trend_keywords')
    op.drop_index(op.f('ix_crawl_tasks_platform'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_keyword_id'), table_name='crawl_tasks')
    op.drop_table('crawl_tasks')
    op.drop_index(op.f('ix_crawl_task_logs_task_id'), table_name='crawl_task_logs')
    op.drop_table('crawl_task_logs')
    op.drop_index(op.f('ix_cleaned_trend_data_source_platform'), table_name='cleaned_trend_data')
    op.drop_index(op.f('ix_cleaned_trend_data_source_id'), table_name='cleaned_trend_data')
    op.drop_index(op.f('ix_cleaned_trend_data_keyword'), table_name='cleaned_trend_data')
    op.drop_index(op.f('ix_cleaned_trend_data_crawl_task_id'), table_name='cleaned_trend_data')
    op.drop_table('cleaned_trend_data')
    op.drop_index(op.f('ix_accounts_platform'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
