from __future__ import annotations

from typing import Protocol, Optional, Sequence

from app.infrastructure.database.models import Account


class AccountRepository(Protocol):
    """Repository interface for Account persistence."""

    async def get_by_id(self, account_id: int) -> Optional[Account]: ...
    async def list_by_platform(self, platform: str, status: Optional[str] = None) -> Sequence[Account]: ...
    async def list_active(self, platform: str) -> Sequence[Account]: ...
    async def create(self, account: Account) -> Account: ...
    async def update(self, account: Account) -> Account: ...
    async def delete(self, account_id: int) -> bool: ...
